
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 102
#define YY_END_OF_BUFFER 103
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[279] =
    {   0,
        0,    0,   93,   93,   98,   98,  103,  102,  100,  101,
       54,  102,   85,   56,   49,  102,   41,   42,   50,   51,
       84,   52,   45,   55,   88,   88,   70,   71,   59,   73,
       60,   69,   87,   39,   40,   65,   87,   87,   87,   87,
       87,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   43,   66,   44,   53,   93,   94,  102,   98,
       99,   64,    0,   91,    0,   86,   76,   67,   81,    0,
        0,   74,   47,   77,   48,   78,   46,    0,   89,   92,
       97,   75,   89,    0,    0,    0,   88,   57,   61,   63,
       62,   58,   87,   82,   87,   87,   87,   87,   87,   87,

       87,   87,   87,    8,   87,   87,   87,   87,   87,   87,
       16,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   83,   68,   93,   95,    0,   96,   98,   90,
       72,    0,    0,    0,   89,    0,   89,   79,   80,   87,
       87,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   87,   14,   87,   87,   18,   87,   87,   87,
       87,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   87,   87,    0,   89,    0,   89,   87,   87,
       87,    1,   87,    3,    5,   87,   87,   87,   87,   10,
       11,   87,   87,   15,   87,   19,   87,   87,   87,   87,

       87,   87,   87,   87,   87,   87,   87,   87,   87,   32,
       87,   87,   35,   87,   87,    2,    4,   87,   87,   87,
       87,   13,   87,   87,   87,   87,   23,   87,   87,   87,
       87,   87,   87,   30,   87,   87,   87,   34,   87,   87,
       87,   87,    9,   12,   17,   87,   87,   22,   24,   25,
       26,   27,   28,   87,   87,   87,   87,   87,   87,   87,
        7,   87,   87,   29,   87,   87,   87,   36,   87,    6,
       20,   21,   31,   33,   38,   87,   37,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,   25,    1,   26,   27,   28,   26,   29,   26,
       26,   26,   30,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       31,   32,   33,   34,   35,    1,   36,   37,   38,   39,

       40,   41,   42,   43,   44,   26,   45,   46,   47,   48,
       49,   50,   26,   51,   52,   53,   54,   55,   56,   57,
       58,   59,   60,   61,   62,   63,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[64] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    3,    1,
        1,    4,    1,    1,    1,    1,    1,    5,    5,    1,
        1,    1,    1,    1,    1,    5,    5,    5,    5,    5,
        1,    1,    1,    1,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    1,
        1,    1,    1
    } ;

static const flex_int16_t yy_base[287] =
    {   0,
        0,    0,   61,   62,  379,  378,  380,  383,  383,  383,
      356,   61,  383,   60,   61,  346,  383,  383,  354,   55,
      383,   56,   69,   58,   73,   78,  383,  383,   54,  353,
       75,  383,    0,  383,  383,  352,   73,  320,  322,   68,
       46,   62,   60,  323,   64,  322,  330,   71,  311,  320,
      318,  323,  383,   59,  383,  383,    0,  383,  104,    0,
      383,  383,  117,  383,  145,  383,  383,  383,  383,  356,
      196,  383,  383,  383,  383,  383,  383,  348,  107,  383,
      383,  383,  111,  115,  124,  143,  147,  340,  383,  383,
      383,  339,    0,  383,  312,  311,  312,  305,  317,  304,

      319,  306,  312,  298,  299,  296,  296,  299,  296,  293,
        0,   82,  297,  115,  295,  110,   87,  299,  292,  101,
      128,  297,  383,  383,    0,  383,  129,  383,    0,  383,
      383,  160,  170,  141,  172,  176,  184,  383,  383,  291,
      292,  302,  288,  300,  295,  283,  154,  297,  295,  291,
      283,  289,  292,    0,  278,  282,    0,  283,  280,  270,
      268,  270,  272,  279,  265,  263,  263,  275,  265,  269,
      266,  272,  274,  263,  190,  192,  194,  196,  262,  257,
      264,    0,  260,    0,    0,  251,  259,  248,  255,    0,
        0,  249,  246,    0,  250,    0,  245,  245,  244,  241,

      253,  243,  247,  252,  251,  249,  239,  241,  222,    0,
      220,  229,    0,  222,  219,    0,    0,  202,  202,  206,
      197,    0,  203,  189,  197,  192,    0,  200,  197,  198,
      182,  191,  191,    0,  182,  185,  183,    0,  186,  177,
      170,  170,    0,    0,    0,  182,  182,    0,    0,    0,
        0,    0,    0,  178,  178,  171,  170,  147,  163,  157,
        0,  141,  131,    0,  141,  131,  108,    0,   81,    0,
        0,    0,    0,    0,    0,   32,    0,  383,  251,  256,
      261,  266,   67,  271,  276,  281
    } ;

static const flex_int16_t yy_def[287] =
    {   0,
      278,    1,  279,  279,  280,  280,  278,  278,  278,  278,
      278,  281,  278,  278,  278,  282,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  283,  278,  278,  278,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  278,  278,  278,  278,  284,  278,  285,  286,
      278,  278,  281,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  283,  278,  283,  283,  283,  283,  283,  283,

      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  278,  278,  284,  278,  285,  278,  286,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  278,  278,  278,  278,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,

      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,    0,  278,  278,
      278,  278,  278,  278,  278,  278
    } ;

static const flex_int16_t yy_nxt[447] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   32,   33,   33,   33,   33,   33,
       34,    8,   35,   36,   37,   38,   39,   40,   41,   42,
       43,   44,   33,   45,   33,   46,   33,   33,   33,   33,
       47,   48,   49,   50,   51,   52,   33,   33,   33,   53,
       54,   55,   56,   58,   58,   64,   66,   73,   68,   80,
       75,   93,   59,   59,   81,   88,   89,   74,   76,   77,
       82,  123,   67,   69,   78,  103,   79,   79,   83,  277,
       84,   84,   65,   83,  104,   87,   87,   91,   92,   95,

       96,   85,   97,  100,  111,  108,   85,  105,  109,  106,
      101,  112,   86,  115,  116,  127,  102,   86,  107,  124,
      128,   64,  165,  117,   79,   79,  118,  156,   79,   79,
       83,  276,   84,   84,  157,  132,  134,  166,  134,  132,
      127,  135,  135,   85,  169,  128,  133,  275,   65,   63,
      133,  163,  170,   63,   86,  136,  159,  136,  135,  135,
      137,  137,   83,  171,   87,   87,  160,  161,  164,   63,
      274,  172,  175,  173,  175,   85,   63,  176,  176,  273,
       63,   63,  177,  272,  177,   63,   86,  178,  178,  135,
      135,  271,   63,  137,  137,   63,  270,   63,  269,   63,

       70,  137,  137,  268,   70,  186,  187,  176,  176,  176,
      176,  178,  178,  178,  178,  267,  266,  265,  264,  263,
       70,  262,  261,  260,  259,  258,  257,   70,  256,  255,
      254,   70,   70,  253,  252,  251,   70,  250,  249,  248,
      247,  246,  245,   70,  244,  243,   70,  242,   70,  241,
       70,   57,   57,   57,   57,   57,   60,   60,   60,   60,
       60,   63,  240,   63,   63,   63,   70,  239,  238,   70,
       70,  125,  237,  125,  236,  125,  126,  126,  126,  126,
      126,  129,  235,  129,  129,  129,  234,  233,  232,  231,
      230,  229,  228,  227,  226,  225,  224,  223,  222,  221,

      220,  219,  218,  217,  216,  215,  214,  213,  212,  211,
      210,  209,  208,  207,  206,  205,  204,  203,  202,  201,
      200,  199,  198,  197,  196,  195,  194,  193,  192,  191,
      190,  189,  188,  185,  184,  183,  182,  181,  180,  179,
      174,  168,  167,  162,  158,  155,  154,  153,  152,  151,
      150,  149,  148,  147,  146,  145,  144,  143,  142,  141,
      140,  139,  138,  131,  130,  122,  121,  120,  119,  114,
      113,  110,   99,   98,   94,   90,   72,   71,   62,  278,
       61,   61,    7,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,

      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278
    } ;

static const flex_int16_t yy_chk[447] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    4,   12,   14,   20,   15,   24,
       22,  283,    3,    4,   24,   29,   29,   20,   22,   22,
       24,   54,   14,   15,   23,   41,   23,   23,   25,  276,
       25,   25,   12,   26,   41,   26,   26,   31,   31,   37,

       37,   25,   37,   40,   45,   43,   26,   42,   43,   42,
       40,   45,   25,   48,   48,   59,   40,   26,   42,   54,
       59,   63,  117,   48,   79,   79,   48,  112,   83,   83,
       84,  269,   84,   84,  112,   79,   85,  117,   85,   83,
      127,   85,   85,   84,  120,  127,   79,  267,   63,   65,
       83,  116,  120,   65,   84,   86,  114,   86,  134,  134,
       86,   86,   87,  121,   87,   87,  114,  114,  116,   65,
      266,  121,  132,  121,  132,   87,   65,  132,  132,  265,
       65,   65,  133,  263,  133,   65,   87,  133,  133,  135,
      135,  262,   65,  136,  136,   65,  260,   65,  259,   65,

       71,  137,  137,  258,   71,  147,  147,  175,  175,  176,
      176,  177,  177,  178,  178,  257,  256,  255,  254,  247,
       71,  246,  242,  241,  240,  239,  237,   71,  236,  235,
      233,   71,   71,  232,  231,  230,   71,  229,  228,  226,
      225,  224,  223,   71,  221,  220,   71,  219,   71,  218,
       71,  279,  279,  279,  279,  279,  280,  280,  280,  280,
      280,  281,  215,  281,  281,  281,  282,  214,  212,  282,
      282,  284,  211,  284,  209,  284,  285,  285,  285,  285,
      285,  286,  208,  286,  286,  286,  207,  206,  205,  204,
      203,  202,  201,  200,  199,  198,  197,  195,  193,  192,

      189,  188,  187,  186,  183,  181,  180,  179,  174,  173,
      172,  171,  170,  169,  168,  167,  166,  165,  164,  163,
      162,  161,  160,  159,  158,  156,  155,  153,  152,  151,
      150,  149,  148,  146,  145,  144,  143,  142,  141,  140,
      122,  119,  118,  115,  113,  110,  109,  108,  107,  106,
      105,  104,  103,  102,  101,  100,   99,   98,   97,   96,
       95,   92,   88,   78,   70,   52,   51,   50,   49,   47,
       46,   44,   39,   38,   36,   30,   19,   16,   11,    7,
        6,    5,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,

      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "assgn4_19CS10071_19CS10072.l"
#line 2 "assgn4_19CS10071_19CS10072.l"
#include<stdio.h>
#include "y.tab.h"
//Keywords
/*
#define KEYWORD_ 100
#define AUTO_ 1
#define BREAK_ 2
#define CASE_ 3
#define CHAR_ 4
#define CONST_ 5
#define CONTINUE_ 6
#define DEFAULT_ 7
#define DO_ 8
#define DOUBLE_ 9
#define ELSE_ 10
#define ENUM_ 11
#define EXTERN_ 12
#define FLOAT_ 13
#define FOR_ 14
#define GOTO_ 15
#define IF_ 16
#define INLINE_ 17
#define INT_ 18
#define LONG_ 19
#define REGISTER_ 20
#define RESTRICT_ 21
#define RETURN_ 22
#define SHORT_ 23
#define SIGNED_ 24
#define SIZEOF_ 25
#define STATIC_ 26
#define STRUCT_ 27
#define SWITCH_ 28
#define TYPEDEF_ 29
#define UNION_ 30
#define UNSIGNED_ 31
#define VOID_ 32
#define VOLATILE_ 33
#define WHILE_ 34
#define BOOL_ 35
#define COMPLEX_ 36
#define IMAGINARY_ 37










//Punctuator
#define SQRBRK_OPEN_ 38
#define SQRBRK_CLOSE_ 39
#define PAREN_OPEN_ 40
#define PAREN_CLOSE_ 41
#define CURBRK_OPEN_ 42
#define CURBRK_CLOSE_ 43
#define DOT_ 44
#define ARROW_ 45
#define INCR_ 46
#define DECR_ 47
#define AND_ 48
#define STAR_ 49
#define PLUS_ 50
#define MINUS_ 51
#define TILDA_ 52
#define NOT_ 53
#define SLASH_ 54
#define PERCENT_ 55
#define LSHFT_ 56
#define RSHFT_ 57
#define LESS_ 58
#define GRTH_ 59
#define LESSE_ 60
#define GRTHE_ 61
#define EQUALS_ 62
#define NOTEQ_ 63
#define XOR_ 64
#define OR_ 65
#define ANDAND_ 66
#define OROR_ 67
#define QUES_ 68
#define COLON_ 69
#define SEMICOLON_ 70
#define TRPDOTS_ 71
#define ASSGN_ 72
#define ASSGNMUL_ 73
#define ASSGNDIV_ 74
#define ASSGNPERCENT_ 75
#define ASSGNPLUS_ 76
#define ASSGNMINUS_ 77
#define ASSGNLSHT_ 78
#define ASSGNRSHT_ 79
#define ASSGNAND_ 80
#define ASSGNXOR_ 81
#define ASSGNOR_ 82
#define COMMA_ 83
#define HASH_ 84   
#define PUNCTUATOR_ 85

//Identifier
#define IDENTIFIER_ 86
#define FLOAT_CONSTANT_ 87
#define CHARACTER_CONSTANT_ 88
#define STRING_LITERAL_ 89
#define ENUMERATION_CONSTANT_ 90
#define INTEGER_CONSTANT_ 91
#define FRACTIONAL_CONSTANT_ 98

#define MULTI_COMMENT_START_  92
#define MULTI_COMMENT_BODY_ 93
#define MULTI_COMMENT_END_ 94
#define SINGLE_COMMENT_START_ 95
#define SINGLE_COMMENT_BODY_ 96
#define SINGLE_COMMENT_END_ 97
*/

int lineNo = 0;
#line 753 "lex.yy.c"

#line 755 "lex.yy.c"

#define INITIAL 0
#define BEGIN_COMMENT_MULTI 1
#define BEGIN_COMMENT_SINGLE 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 154 "assgn4_19CS10071_19CS10072.l"



#line 978 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 279 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 383 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 157 "assgn4_19CS10071_19CS10072.l"
{return AUTO_;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 158 "assgn4_19CS10071_19CS10072.l"
{return BREAK_;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 159 "assgn4_19CS10071_19CS10072.l"
{return CASE_;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 160 "assgn4_19CS10071_19CS10072.l"
{return CONST_;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 161 "assgn4_19CS10071_19CS10072.l"
{return CHAR_;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 162 "assgn4_19CS10071_19CS10072.l"
{return CONTINUE_;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 163 "assgn4_19CS10071_19CS10072.l"
{return DEFAULT_;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 164 "assgn4_19CS10071_19CS10072.l"
{return DO_;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 165 "assgn4_19CS10071_19CS10072.l"
{return DOUBLE_;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 166 "assgn4_19CS10071_19CS10072.l"
{return ELSE_;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 167 "assgn4_19CS10071_19CS10072.l"
{return ENUM_;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 168 "assgn4_19CS10071_19CS10072.l"
{return EXTERN_;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 169 "assgn4_19CS10071_19CS10072.l"
{return FLOAT_;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 170 "assgn4_19CS10071_19CS10072.l"
{return FOR_;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 171 "assgn4_19CS10071_19CS10072.l"
{return GOTO_;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 172 "assgn4_19CS10071_19CS10072.l"
{return IF_;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 173 "assgn4_19CS10071_19CS10072.l"
{return INLINE_;} 
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 174 "assgn4_19CS10071_19CS10072.l"
{return INT_;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 175 "assgn4_19CS10071_19CS10072.l"
{return LONG_;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 176 "assgn4_19CS10071_19CS10072.l"
{return REGISTER_;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 177 "assgn4_19CS10071_19CS10072.l"
{return RESTRICT_;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 178 "assgn4_19CS10071_19CS10072.l"
{return RETURN_;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 179 "assgn4_19CS10071_19CS10072.l"
{return SHORT_;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 180 "assgn4_19CS10071_19CS10072.l"
{return SIGNED_;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 181 "assgn4_19CS10071_19CS10072.l"
{return SIZEOF_;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 182 "assgn4_19CS10071_19CS10072.l"
{return STATIC_;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 183 "assgn4_19CS10071_19CS10072.l"
{return STRUCT_;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 184 "assgn4_19CS10071_19CS10072.l"
{return SWITCH_;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 185 "assgn4_19CS10071_19CS10072.l"
{return TYPEDEF_;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 186 "assgn4_19CS10071_19CS10072.l"
{return UNION_;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 187 "assgn4_19CS10071_19CS10072.l"
{return UNSIGNED_;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 188 "assgn4_19CS10071_19CS10072.l"
{return VOID_;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 189 "assgn4_19CS10071_19CS10072.l"
{return VOLATILE_;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 190 "assgn4_19CS10071_19CS10072.l"
{return WHILE_;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 191 "assgn4_19CS10071_19CS10072.l"
{return BOOL_;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 192 "assgn4_19CS10071_19CS10072.l"
{return COMPLEX_;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 193 "assgn4_19CS10071_19CS10072.l"
{return IMAGINARY_;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 194 "assgn4_19CS10071_19CS10072.l"
{return KEYWORD_;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 196 "assgn4_19CS10071_19CS10072.l"
{return SQRBRK_OPEN_ ;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 197 "assgn4_19CS10071_19CS10072.l"
{return SQRBRK_CLOSE_ ;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 198 "assgn4_19CS10071_19CS10072.l"
{return PAREN_OPEN_ ;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 199 "assgn4_19CS10071_19CS10072.l"
{return PAREN_CLOSE_ ;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 200 "assgn4_19CS10071_19CS10072.l"
{return CURBRK_OPEN_ ;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 201 "assgn4_19CS10071_19CS10072.l"
{return CURBRK_CLOSE_ ;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 202 "assgn4_19CS10071_19CS10072.l"
{return DOT_ ;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 203 "assgn4_19CS10071_19CS10072.l"
{return ARROW_ ;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 204 "assgn4_19CS10071_19CS10072.l"
{return INCR_ ;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 205 "assgn4_19CS10071_19CS10072.l"
{return DECR_ ;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 206 "assgn4_19CS10071_19CS10072.l"
{return AND_ ;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 207 "assgn4_19CS10071_19CS10072.l"
{return STAR_ ;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 208 "assgn4_19CS10071_19CS10072.l"
{return PLUS_ ;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 209 "assgn4_19CS10071_19CS10072.l"
{return MINUS_ ;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 210 "assgn4_19CS10071_19CS10072.l"
{return TILDA_ ;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 211 "assgn4_19CS10071_19CS10072.l"
{return NOT_ ;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 212 "assgn4_19CS10071_19CS10072.l"
{return SLASH_ ;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 213 "assgn4_19CS10071_19CS10072.l"
{return PERCENT_ ;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 214 "assgn4_19CS10071_19CS10072.l"
{return LSHFT_ ;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 215 "assgn4_19CS10071_19CS10072.l"
{return RSHFT_ ;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 216 "assgn4_19CS10071_19CS10072.l"
{return LESS_ ;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 217 "assgn4_19CS10071_19CS10072.l"
{return GRTH_ ;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 218 "assgn4_19CS10071_19CS10072.l"
{return LESSE_ ;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 219 "assgn4_19CS10071_19CS10072.l"
{return GRTHE_ ;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 220 "assgn4_19CS10071_19CS10072.l"
{return EQUALS_ ;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 221 "assgn4_19CS10071_19CS10072.l"
{return NOTEQ_ ;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 222 "assgn4_19CS10071_19CS10072.l"
{return XOR_ ;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 223 "assgn4_19CS10071_19CS10072.l"
{return OR_ ;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 224 "assgn4_19CS10071_19CS10072.l"
{return ANDAND_ ;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 225 "assgn4_19CS10071_19CS10072.l"
{return OROR_ ;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 226 "assgn4_19CS10071_19CS10072.l"
{return QUES_ ;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 227 "assgn4_19CS10071_19CS10072.l"
{return COLON_ ;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 228 "assgn4_19CS10071_19CS10072.l"
{return SEMICOLON_ ;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 229 "assgn4_19CS10071_19CS10072.l"
{return TRPDOTS_ ;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 230 "assgn4_19CS10071_19CS10072.l"
{return ASSGN_ ;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 231 "assgn4_19CS10071_19CS10072.l"
{return ASSGNMUL_ ;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 232 "assgn4_19CS10071_19CS10072.l"
{return ASSGNDIV_ ;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 233 "assgn4_19CS10071_19CS10072.l"
{return ASSGNPERCENT_ ;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 234 "assgn4_19CS10071_19CS10072.l"
{return ASSGNPLUS_ ;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 235 "assgn4_19CS10071_19CS10072.l"
{return ASSGNMINUS_ ;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 236 "assgn4_19CS10071_19CS10072.l"
{return ASSGNLSHT_ ;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 237 "assgn4_19CS10071_19CS10072.l"
{return ASSGNRSHT_ ;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 238 "assgn4_19CS10071_19CS10072.l"
{return ASSGNAND_ ;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 239 "assgn4_19CS10071_19CS10072.l"
{return ASSGNXOR_ ;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 240 "assgn4_19CS10071_19CS10072.l"
{return ASSGNOR_ ;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 241 "assgn4_19CS10071_19CS10072.l"
{return COMMA_ ;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 242 "assgn4_19CS10071_19CS10072.l"
{return HASH_ ;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 243 "assgn4_19CS10071_19CS10072.l"
{return PUNCTUATOR_;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 244 "assgn4_19CS10071_19CS10072.l"
{return IDENTIFIER_;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 245 "assgn4_19CS10071_19CS10072.l"
{return INTEGER_CONSTANT_;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 246 "assgn4_19CS10071_19CS10072.l"
{return FLOAT_CONSTANT_;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 247 "assgn4_19CS10071_19CS10072.l"
{return CHARACTER_CONSTANT_;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 248 "assgn4_19CS10071_19CS10072.l"
{return STRING_LITERAL_;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 249 "assgn4_19CS10071_19CS10072.l"
{BEGIN(BEGIN_COMMENT_MULTI);}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 250 "assgn4_19CS10071_19CS10072.l"
{}
	YY_BREAK
case 94:
/* rule 94 can match eol */
YY_RULE_SETUP
#line 251 "assgn4_19CS10071_19CS10072.l"
{lineNo++;}
	YY_BREAK
case 95:
/* rule 95 can match eol */
YY_RULE_SETUP
#line 252 "assgn4_19CS10071_19CS10072.l"
{}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 253 "assgn4_19CS10071_19CS10072.l"
{BEGIN(INITIAL);}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 254 "assgn4_19CS10071_19CS10072.l"
{BEGIN(BEGIN_COMMENT_SINGLE);}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 255 "assgn4_19CS10071_19CS10072.l"
{}
	YY_BREAK
case 99:
/* rule 99 can match eol */
YY_RULE_SETUP
#line 256 "assgn4_19CS10071_19CS10072.l"
{BEGIN(INITIAL);lineNo++;}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 257 "assgn4_19CS10071_19CS10072.l"
{}
	YY_BREAK
case 101:
/* rule 101 can match eol */
YY_RULE_SETUP
#line 258 "assgn4_19CS10071_19CS10072.l"
{lineNo++;}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 259 "assgn4_19CS10071_19CS10072.l"
ECHO;
	YY_BREAK
#line 1549 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(BEGIN_COMMENT_MULTI):
case YY_STATE_EOF(BEGIN_COMMENT_SINGLE):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 279 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 279 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 278);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 259 "assgn4_19CS10071_19CS10072.l"


/*

int main()
{
    int curr;
    while(curr=yylex())
    {
        switch(curr){
            case KEYWORD_ :printf("<KEYWORD,%s>\n",yytext);break;
            //Identifier            
            case IDENTIFIER_ :  printf("<IDENTIFIER, %s>\n",yytext);break;
            //Constants
            case FRACTIONAL_CONSTANT_ : printf("<FRACTIONAL_CONSTANT, %s>\n",yytext);break;
            case FLOAT_CONSTANT_ : printf("<FLOAT, %s>\n",yytext);break;
            case CHARACTER_CONSTANT_ :printf("<CHARACTER_CONSTANT_, %s>\n",yytext);break;
            case STRING_LITERAL_ : printf("<STRING_LITERAL, %s>\n",yytext);break;
            case ENUMERATION_CONSTANT_ : printf("<ENUMERATION_CONSTANT, %s>\n",yytext);break;
            case INTEGER_CONSTANT_ : printf("<INTEGER_CONSTANT, %s>\n",yytext);break;
            //Comments
            case MULTI_COMMENT_START_ : printf("<MULTI_COMMENT_START>\n");break;
            case MULTI_COMMENT_BODY_ : printf("<MULTI_COMMENT_BODY,%s>\n",yytext);break;
            case MULTI_COMMENT_END_ : printf("<MULTI_COMMENT_END>\n");break;
            case SINGLE_COMMENT_START_ : printf("<SINGLE_COMMENT_START>\n");break;
            case SINGLE_COMMENT_BODY_ : printf("<SINGLE_COMMENT_BODY,%s>\n",yytext);break;
            case SINGLE_COMMENT_END_ : printf("<SINGLE_COMMENT_END>\n");break;
            //Keywords
            case AUTO_ : printf("<KEYWORD,AUTO>\n");break;
            case BREAK_ : printf("<KEYWORD,BREAK>\n");break;
            case CASE_ : printf("<KEYWORD,CASE>\n");break;
            case CHAR_ : printf("<KEYWORD,CHAR>\n");break;
            case CONST_ : printf("<KEYWORD,CONST>\n");break;
            case CONTINUE_ : printf("<KEYWORD,CONTINUE>\n");break;
            case DEFAULT_ : printf("<KEYWORD,DEFAULT>\n");break;
            case DO_ : printf("<KEYWORD,DO>\n");break;
            case DOUBLE_ : printf("<KEYWORD,DOUBLE>\n");break;
            case ELSE_ : printf("<KEYWORD,ELSE>\n");break;
            case ENUM_ : printf("<KEYWORD,ENUM>\n");break;
            case EXTERN_ : printf("<KEYWORD,EXTERN>\n");break;
            case FLOAT_ : printf("<KEYWORD,FLOAT>\n");break;
            case FOR_ : printf("<KEYWORD,FOR>\n");break;
            case GOTO_ : printf("<KEYWORD,GOTO>\n");break;
            case IF_ : printf("<KEYWORD,IF>\n");break;
            case INLINE_ : printf("<KEYWORD,INLINE>\n");break;
            case INT_ : printf("<KEYWORD,INT>\n");break;
            case LONG_: printf("<KEYWORD,LONG>\n");break;
            case REGISTER_ : printf("<KEYWORD,REGISTER_>\n");break;
            case RESTRICT_ :printf("<KEYWORD,RESTRICT>\n");break;
            case RETURN_ :printf("<KEYWORD,RETURN>\n");break;
            case SHORT_ :printf("<KEYWORD,SHORT>\n");break;
            case SIGNED_ :printf("<KEYWORD,SIGNED>\n");break;
            case SIZEOF_ :printf("<KEYWORD,SIZEOF>\n");break;
            case STATIC_ :printf("<KEYWORD,STATIC>\n");break;
            case STRUCT_ :printf("<KEYWORD,STRUCT>\n");break;
            case SWITCH_ :printf("<KEYWORD,SWITCH>\n");break;
            case TYPEDEF_ :printf("<KEYWORD,TYPEDEF>\n");break;
            case UNION_ :printf("<KEYWORD,UNION>\n");break;
            case UNSIGNED_ :printf("<KEYWORD,UNSIGNED>\n");break;
            case VOID_ :printf("<KEYWORD,VOID>\n");break;
            case VOLATILE_ :printf("<KEYWORD,VOLATILE\n");break;
            case WHILE_ :printf("<KEYWORD,WHILE\n");break;
            case BOOL_ :printf("<KEYWORD,BOOL\n");break;
            case COMPLEX_ :printf("<KEYWORD,COMPLEX_\n");break;
            case IMAGINARY_ :printf("<KEYWORD,IMAGINARY\n");break;
            //Punctuators
            case SQRBRK_OPEN_ :printf("<PUNCTUATOR,%s>\n",yytext);break;
            case SQRBRK_CLOSE_ :printf("<PUNCTUATOR,%s>\n",yytext);break;
            case PAREN_OPEN_ :printf("<PUNCTUATOR,%s>\n",yytext);break;
            case PAREN_CLOSE_ :printf("<PUNCTUATOR,%s>\n",yytext);break;
            case CURBRK_OPEN_ :printf("<PUNCTUATOR,%s>\n",yytext);break;
            case CURBRK_CLOSE_ :printf("<PUNCTUATOR,%s>\n",yytext);break;
            case DOT_ :printf("<PUNCTUATOR,%s>\n",yytext);break;
            case ARROW_ :printf("<PUNCTUATOR,%s>\n",yytext);break;
            case INCR_ :printf("<PUNCTUATOR,%s>\n",yytext);break;
            case DECR_ :printf("<PUNCTUATOR,%s>\n",yytext);break;
            case AND_ :printf("<PUNCTUATOR,%s>\n",yytext);break;
            case STAR_ :printf("<PUNCTUATOR,%s>\n",yytext);break;
            case PLUS_ :printf("<PUNCTUATOR,%s>\n",yytext);break;
            case MINUS_ :printf("<PUNCTUATOR,%s>\n",yytext);break;
            case TILDA_ :printf("<PUNCTUATOR,%s>\n",yytext);break;
            case NOT_ :printf("<PUNCTUATOR,%s>\n",yytext);break;
            case SLASH_ :printf("<PUNCTUATOR,%s>\n",yytext);break;
            case PERCENT_ :printf("<PUNCTUATOR,%s>\n",yytext);break;
            case LSHFT_ :printf("<PUNCTUATOR,%s>\n",yytext);break;
            case RSHFT_ :printf("<PUNCTUATOR,%s>\n",yytext);break;
            case LESS_ :printf("<PUNCTUATOR,%s>\n",yytext);break;
            case GRTH_ :printf("<PUNCTUATOR,%s>\n",yytext);break;
            case LESSE_ :printf("<PUNCTUATOR,%s>\n",yytext);break;
            case GRTHE_ :printf("<PUNCTUATOR,%s>\n",yytext);break;
            case EQUALS_ :printf("<PUNCTUATOR,%s>\n",yytext);break;
            case NOTEQ_ :printf("<PUNCTUATOR,%s>\n",yytext);break;
            case XOR_ :printf("<PUNCTUATOR,%s>\n",yytext);break;
            case OR_ :printf("<PUNCTUATOR,%s>\n",yytext);break;
            case ANDAND_ :printf("<PUNCTUATOR,%s>\n",yytext);break;
            case OROR_ :printf("<PUNCTUATOR,%s>\n",yytext);break;
            case QUES_ :printf("<PUNCTUATOR,%s>\n",yytext);break;
            case COLON_ :printf("<PUNCTUATOR,%s>\n",yytext);break;
            case SEMICOLON_ :printf("<PUNCTUATOR,%s>\n",yytext);break;
            case TRPDOTS_ :printf("<PUNCTUATOR,%s>\n",yytext);break;
            case ASSGN_ :printf("<PUNCTUATOR,%s>\n",yytext);break;
            case ASSGNMUL_ :printf("<PUNCTUATOR,%s>\n",yytext);break;
            case ASSGNDIV_ :printf("<PUNCTUATOR,%s>\n",yytext);break;
            case ASSGNPERCENT_ :printf("<PUNCTUATOR,%s>\n",yytext);break;
            case ASSGNPLUS_ :printf("<PUNCTUATOR,%s>\n",yytext);break;
            case ASSGNMINUS_ :printf("<PUNCTUATOR,%s>\n",yytext);break;
            case ASSGNLSHT_ :printf("<PUNCTUATOR,%s>\n",yytext);break;
            case ASSGNRSHT_ :printf("<PUNCTUATOR,%s>\n",yytext);break;
            case ASSGNAND_ :printf("<PUNCTUATOR,%s>\n",yytext);break;
            case ASSGNXOR_ :printf("<PUNCTUATOR,%s>\n",yytext);break;
            case ASSGNOR_ :printf("<PUNCTUATOR,%s>\n",yytext);break;
            case COMMA_ :printf("<PUNCTUATOR,%s>\n",yytext);break;
            case HASH_ :printf("<PUNCTUATOR,%s>\n",yytext);break;
            case PUNCTUATOR_ :printf("<PUNCTUATOR,%s>\n",yytext);break;

        }
    }
    return 0;
    //
}


*/
